/*
 * @Description: 
 * @Author: 爱酱丶
 * @Date: 2025-04-14 14:21:12
 * @LastEditTime: 2025-04-17 11:50:21
 * @LastEditors: 爱酱丶
 */
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// #define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_NC // I2S_LRCK (GPIO45)
// #define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_2  // I2S_MCLK (GPIO2)
// #define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_15 // I2S_CODEC_DSDIN (GPIO15)
// #define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_16 // I2S_ADC_SDOU (GPIO16)
// #define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_17 // I2S_SCLK (GPIO17)
// #define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_45 // I2S_LRCK (GPIO45)

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_2
#define AUDIO_I2S_GPIO_LRCK GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_ADC_SDOUT GPIO_NUM_16
#define AUDIO_I2S_CODEC_DSDIN GPIO_NUM_15

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#else

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_15
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_16

#endif

#define BUILTIN_LED_GPIO        GPIO_NUM_41 //这个有问题，先设置为47
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_38
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define DISPLAY_SDA_PIN GPIO_NUM_6
#define DISPLAY_SCL_PIN GPIO_NUM_7
#define DISPLAY_WIDTH   128


#define DISPLAY_HEIGHT  64

#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false


#define ML307_RX_PIN GPIO_NUM_44
#define ML307_TX_PIN GPIO_NUM_43
#define ML307_POWER GPIO_NUM_36

// #define DISPLAY_WIDTH   320
// #define DISPLAY_HEIGHT  240
// #define DISPLAY_MIRROR_X true
// #define DISPLAY_MIRROR_Y true
// #define DISPLAY_SWAP_XY false

// #define DISPLAY_OFFSET_X  0
// #define DISPLAY_OFFSET_Y  0

// #define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
// #define DISPLAY_BACKLIGHT_OUTPUT_INVERT false



#endif // _BOARD_CONFIG_H_
